baseURL = "https://kang-lyk.github.io/blog/"
languageCode = "zh-CN"
#title = ""
title = "枯木逢春犹再发，人无两度再少年"
theme = "sugoi"

[menu]
    [[menu.nav]]
        name = "首页"
        url = "/"
        weight = "2"
    [[menu.nav]]
        name = "博文"
        url = "post"
        weight = "1"